# Generated by Django 6.0.3 on 2026-05-11 09:09

import payments.models
from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


def backfill_payment_splits(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    for payment in Payment.objects.all().iterator():
        amount = Decimal(payment.amount or 0).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        rate = Decimal(payment.commission_rate or 10)
        commission = ((amount * rate) / Decimal('100')).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        payment.commission_amount = commission
        payment.studio_payout_amount = (amount - commission).quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)
        if payment.status == 'Completed' and payment.payout_status == 'Pending':
            payment.payout_status = 'Ready'
        payment.save(update_fields=['commission_amount', 'studio_payout_amount', 'payout_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_gateway_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=payments.models.default_commission_rate, max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='payout_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payout_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payout_reference',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payout_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready for Payout'), ('Paid', 'Paid to Studio'), ('Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='studio_payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(backfill_payment_splits, migrations.RunPython.noop),
    ]
